apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-minikube-app
  title: Create a new application running on minikube 
  description: Create a new application running on minikube
  tags: ['recommended']
spec:
  owner: guests
  type: service
  parameters:
    - title: Application Name
      required:
         - AppName
         - NameSpace
         
      properties:
        AppName:
          title: Application name.
          type: string
          description: Name of the Application to be created.
          ui:autofocus: true
          ui:options:
            rows: 5

        NameSpace:
          title:  NameSpace
          type: string
          description: Name Space
          default: "default"

    - title: Choose a Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Location of the repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
# Getting the all the files/details from the template
    - id: fetch-base
      name: Fetching Details from content folder
      action: fetch:template
      input:
        url: ./content  # Location of the content directory where catlog-info.yaml file is present for the template
        copyWithoutRender:
          - .github/workflows/*
        values:
          name: ${{ parameters.AppName}}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

# Publish the content of the current working directory to our github directory
    - id: publish
      name: Publishing Details
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This repo is to create an app using backstage.
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public # or 'internal' or 'private'
        # defaultBranch: master

# Triggering CI-CD to create resource in our case github action. 
    # - id: github-action
    #   name: Starting GitHub action
    #   action: github:actions:dispatch
    #   input:
    #     workflowId:  terraform.yaml # ID of GitHub action WorkFlow
    #     repoUrl: 'github.com?repo=idp-terraform&owner=devops-converge'
    #     branchOrTagName: 'main'
    #     workflowInputs:
    #       S3Name: ${{ parameters.S3Name }}
    #       awsRegion: ${{ parameters.Region }}
    #       action: ${{ parameters.action }}

# Registering new component in the catalog of backstage.
    - id: register
      name: Registering the new Component 
      action: catalog:register
      input:
        repoContentsUrl: ${{steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/component-info.yaml' # where the info of the catalog is stored.

# Output links  are displayed to the user after the template execution.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
