version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "{{ cookiecutter.component_id }}"
s3_prefix = "{{ cookiecutter.component_id }}"
region = "{{ cookiecutter.region }}"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"